from utils import *
from collections import Counter
loadj=lambda f:json.loads((ROOT/f).read_text(encoding='utf-8'))
manifest=loadj('研究清单.json');M=loadj('measurement_results.json');DC=loadj('daily_conditional_coefficients.json');FC=loadj('factor_coefficients.json');MC=loadj('macro_coefficients.json');FU=loadj('fund_coefficients.json');HR=loadj('hourly_lead_results.json');IA=loadj('inference_audit.json');sources={x['id']:x for x in loadj('literature_sources.json')}
rows={}
def add(i,finding,counter,limit,file,data,kind='实证',strength='有限或未确立'):
 r=dict(manifest[i-1]);r.update(status='completed',kind=kind,evidence_strength=strength,finding=finding,countercheck=counter,limitation=limit,evidence_file=file,evidence=data);rows[i]=r
def selected(file,**filters):
 a=loadj(file);return [x for x in a if all(x.get(k)==v for k,v in filters.items())]
def test(i,file,filters,finding,counter,limit='历史样本外检验不是前瞻盲测；不显著不能证明效应为零。'):
 data=selected(file,**filters);assert data
 add(i,finding,counter,limit,file,data)
def mc(i,factors,statement):
 data={k:{'n':v['n'],'first':v['first'],'last':v['last'],'coefficients':[a for a in v['coefficients'] if a['factor'] in factors]} for k,v in MC.items() if k.endswith('_extended')}
 add(i,statement,'采用同一样本、同一组宏观控制，分别估计黄金、白银和比值；检查区块区间。','同期条件关联不能解释为政策冲击的因果效应，也不能直接当提前信号。','macro_coefficients.json',data)
def lit(i,ids,finding,counter,limit):
 add(i,finding,counter,limit,'literature_sources.json',[sources[x] for x in ids],kind='文献及识别审查',strength='有来源支持，适用范围受限')
add(1,'Δln(金银比)=黄金对数收益−白银对数收益；比值升高只确定黄金相对白银更强。','比值均升 2% 的对数幅度，黄金可以涨 1%，也可以跌 1%。','这是恒等式；不规定经济冲击、未来收益或套利利润。','measurement_results.json',M['identity'],'数学','确定')
add(2,'相同 5 点变化，从 40 起步是 12.5%，从 100 起步是 5%；点数速度不能跨时期直接比较。','同时核对普通百分比与对数变化；对数速度适合相加分解。','标准化异常仍依赖历史窗口，不能自动成为情绪量表。','measurement_results.json',M['identity']['equal_point_change'],'数学','确定')
add(3,'同一时刻共同换算汇率 k 时，(kG)/(kS)=G/S；美元的经济冲击仍可因金银敏感度不同而改变比值。','数值换算不变性与多因子美元差异系数分开检查。','抵消的是计价换算，不是金银对美元冲击的全部反应。','macro_coefficients.json',MC['qret20_extended'],'数学与实证','恒等部分确定；经济部分有条件')
add(4,'黄金收益、白银收益和比值收益三列只有两个独立方向；将三者同时无约束回归会产生精确共线性。','直接检查价格序列生成的设计矩阵秩，并与收益恒等式对照。','非线性特征、不同滞后和不同信息源可以包含新信息，不能据此说所有比值模型都无用。','measurement_results.json',M['identity'],'数学','确定')
add(5,'控制同一个黄金收益和常数后，比值收益残差恰等于白银收益残差的负值。','两次独立投影的残差相加误差接近浮点精度。','残差异常仍可能有预测价值；但它不是不含金银信息的独立第三种资产。','measurement_results.json',{'max_error':M['residual_equivalence_max_error']},'数学','确定')
add(6,'比值风险由金银各自方差和二者协方差共同构成，不能把变快全部归因于黄金风险。','分期核对 Var(g−s)=Var(g)+Var(s)−2Cov(g,s)。','历史协方差会变；此恒等式不识别协方差变化的原因。','measurement_results.json',M['variance_decomposition'],'数学与实证','恒等部分确定')
add(7,'一比一名义金额价差不是最小方差黄金对冲；本样本滚动白银对冲系数中位数约 0.47。','以前一期估计的系数计算后一期价差风险，与固定一比一比较。','这是历史风险比较，未计融资、保证金、交易成本，也不保证压力期对冲效果。','measurement_results.json',M['hedge'],'实证','样本支持')
add(8,'期货每份未平仓合约同时对应一个多头与空头；某类别净多增加不代表全市场凭空增加净多。','2,042 条报告中，多头和空头分别加总到未平仓量。','价格由边际成交和流动性形成，会计平衡不意味着价格不受交易影响。','measurement_results.json',M['accounting'],'会计','确定')
add(9,'净多占未平仓量比例与净多合约变化会因分母变化出现相反方向。','1,020 个变化周期中，黄金 95 次、白银 68 次方向不一致；分子分母分解误差接近零。','方向不一致不等于数据错误，也不能据比例变化推断成交净流出金额。','measurement_results.json',M['denominator'],'会计与实证','确定且样本验证')
add(10,'预测误差下降不保证方向正确，更不保证扣费后的交易收益。','真实收益 +0.1%；预测由 −1% 改为 −0.1% 时平方误差显著下降，但据预测做空仍亏损。','本研究评价统计预测，未构建或宣称盈利交易策略。','measurement_results.json',{'actual':.001,'old':-.01,'new':-.001,'old_mse':.011**2,'new_mse':.002**2},'数学反例','确定')
add(11,'ETF 每份代表的金银数量不同，ETF 价格比不能套用现货 60、80 等水平。','将 ETF 月均价格比与世界银行美元/盎司比值匹配，检查比例及漂移。','费用、每份含量、报价时点和跟踪误差令长期比例也不是严格常数。','measurement_results.json',M['measurement'],'测量','样本支持')
add(12,'月均黄金价除以月均白银价不等于每日金银比的月均值。','在同一个 ETF 日线样本同时聚合两种口径，保留最大与典型差异。','本次测量差异不是现货月均数据质量错误；长期结果需遵守原数据定义。','measurement_results.json',M['measurement'],'测量','确定且样本验证')
add(13,'ETF 与连续期货的相对变化高度相关但不相同，不能将差异直接称为市场先后。','同时比较共同日和周聚合相关；前序轮次也换发行人重跑模型。','合约切换、结算时点、基金费用可能造成偏差；连续期货并非无成本可持有组合。','measurement_results.json',M['measurement'],'测量','样本支持')
add(14,'只把白银报价时钟错移一段，就能把很强的同期联系伪装成黄金领先。','负面对照保留原价格，只移动时间标签；真实同步相关与伪造领先相关均约 0.81。','此为故意制造的时间错误示例，绝不是观测到真实领先 0.81。','hourly_lead_results.json',HR['descriptions'],'测量反例','确定且样本验证')
add(15,'开收盘收益平方会漏掉日内先涨后跌；约三成完整日的终点平方小于分时平方和的四分之一。','逐日比较开收盘平方与 7 段收益平方和。','小时平方和仍遗漏小时内部路径，也不等于逐笔真实积分方差。','measurement_results.json',M['hourly_measurement']['GLD_SLV']['risk'],'测量','样本支持')
add(16,'此 ETF 完整日样本中，隔夜平方项占粗粒度总平方风险约 65%，忽略隔夜会改变研究对象。','分别计算金银总和占比与逐日中位数，不将隔夜净变动当连续隔夜 RV。','缺失极端日、ETF 交易时段及隔夜净额口径限制该比例向国际全天市场外推。','measurement_results.json',M['hourly_measurement']['GLD_SLV']['risk'],'测量','局部样本支持')
add(17,'开盘、盘中、尾盘风险必须按交易分钟数比较；最后一段只有 30 分钟。','逐时段统计每分钟收益平方，并在不同发行人的样本重复。','每分钟平方只是粗粒度风险密度，不是可直接交易的波动率。','measurement_results.json',{p:x['by_slot'] for p,x in M['hourly_measurement'].items()},'测量','局部样本支持')
add(18,'501 个交易日期只有 493 个完整日，2026-01-30 与 02-02 的缺失尤其限制压力检验。','日线收盘交叉核对；不完整日 RV 和碰到缺失日的未来窗口保持缺失，不填成低风险。','2026-01-30 日线金银跌幅约 10.27% / 28.54%，小时样本遗漏重大极端事件，不能声称覆盖全部危机。','measurement_results.json',M['hourly_measurement']['GLD_SLV']['excluded_days_daily_returns'],'数据审计','明确限制')
add(19,'同一段美元、利率变化解释同期金价，和昨天数据预测明天价格属于不同问题。','宏观 *0 回归与至少滞后一日的预测回归分开；比较二者符号和区间。','昨日数据在历史库中也可能修订；未取得全部初始版本。','macro_coefficients.json',{'contemporaneous':MC['gret20_extended'],'predictive':FC['future_return20']},'信息时间','确定的识别区分')
add(20,'COT 截至日期与公众可用日期不一样；本批次有效特征使用距截至日 10—17 天的保守观测。','核对年龄分布，且停发窗口和过旧观测不可用。','保守日期不是完整实际发布档案；本批次广义样本含少量非周二截至日，年龄上限不同于前序模型筛选后的 16 天。','measurement_results.json',M['timing'],'信息时间','明确限制')
add(21,'长期比值中心跨阶段明显变化，固定数字不具有已验证的跨年代稳定性。','预定四个时间段的比值中位数约 39.71、70.72、62.27、82.48。','分组差异不是正式证明所有均值回归模型无效；均衡本身可以时变。','measurement_results.json',M['decade_ratio'],'实证','较强描述证据')
add(22,'对数金价对对数银价的分期斜率并不总接近 1；样本斜率约 0.98、0.55、0.67、0.97。','保留每段区块区间，而不是只报告全样本一条回归线。','非平稳价格水平回归可能伪回归；本项没有将普通 OLS 区间当成协整检验。','measurement_results.json',M['long_coefficients'],'实证','描述性，非协整确证')
add(23,'按四段 AR 点估计得到的半衰期约 34、29、15、6 个月，无法支持固定等待期。','只在 0<φ<1 时计算半衰期，并保留参数区间和结构变化说明。','短期 AR 估计偏差、近单位根与断点会扭曲半衰期；它不是到期兑现承诺。','measurement_results.json',M['long_coefficients'],'实证','描述性，稳定性不足')
add(24,'滚动长期偏离未建立稳定的比值回落预测：12 个月比值误差全样本约降 1.64%，区间跨零。','2017 年以后同项误差反而上升；本轮以月末信息时间重算。','月均价收益是统计对象，保留整月空档仍不是可直接成交的月末策略。','measurement_results.json',[x for x in M['monthly_predictive_results'] if x['target']=='ratio_12' and x['model']=='level'])
add(25,'将高、低偏离分开没有稳定改善长期预测。','对黄金、白银和比值分别比较线性偏离与正负分项；全样本增加误差。','缺少改善不能证明真实调整完全对称；有限时期和共线性降低辨别能力。','measurement_results.json',[x for x in M['monthly_predictive_results'] if x['model']=='asymmetric' and x['period']=='all'])
add(26,'长期偏离对未来白银的点预测改善比黄金更明显，但区间和校正不足以确立固定调整承担者。','白银 12 个月误差约降 5.28%，黄金约增 4.53%；分别估计调整系数。','金银未来收益高度相关，单一系数的显著与否不是两系数差异的正式检验。','measurement_results.json',M['monthly_adjustment_coefficients'])
mc(27,['real0'],'实际利率上升对金银同期收益均为负关联；二者差异小，不能由此确定比值方向。')
mc(28,['dollar0'],'美元增强与金银同期收益负相关；相对差异为正的点估计区间跨零，不能固定套用。')
mc(29,['sp0'],'控制美元、利率、VIX、GVZ及商品因素后，美股对比值的独立同期系数不稳定。')
mc(30,['vix0','gvz0'],'股市风险和黄金自身风险不是同一因子；同时放入后，比值同期系数均存在较大不确定性。')
mc(31,['breakeven0'],'控制实际利率及其他市场后，通胀预期对比值的独立同期关联尚未明确。')
mc(32,['copper0'],'铜价上行对白银的同期正关联大于黄金，对比值的条件系数为负且该区间不跨零。')
mc(33,['oil0'],'油价上行与比值下降存在条件关联，但油价包含供给和地缘冲击，不能等同增长情绪。')
add(34,'预设 VIX 上升、下降分项后保留全部系数；关系并非可由一个统一“恐慌系数”稳定概括。','比较线性、正负分项及同样本宏观控制，不挑选最好状态。','分项不同不自动构成系数相等的拒绝；本项是探索性状态审查。','macro_coefficients.json',{k:v for k,v in MC.items() if k.endswith('asymmetry')})
add(35,'按既有文献提出的 2017 候选日期切分，宏观与长期预测的大小和表现发生变化。','保留前后全部系数；长期比值预测并未在两个时期均改善。','断点日期来自已发表研究，非当时可知的实盘规则，也非本样本最优断点。','macro_coefficients.json',{k:v for k,v in MC.items() if k.endswith(('pre2017','post2017'))})
test(36,'daily_results.json',{'model':'speed','metric':'MSE'},'比值速度在强基准之外未形成稳定收益或风险预测改善。','同时检查 5/20 日风险、20 日金价、比值和上下尾部，保留不利结果。')
test(37,'daily_results.json',{'model':'accel','metric':'MSE'},'已含速度时再加加速度，主样本多个目标的误差均略增。','比较对象明确是含速度模型，不把相同信息换一种写法当成新增领先。')
test(38,'daily_results.json',{'model':'standard','metric':'MSE'},'按历史尺度标准化便于跨时期解释，但没有保证预测增量。','与未经标准化的绝对变化幅度对照；收益小幅改善的区间跨零。')
test(39,'daily_results.json',{'model':'residual','metric':'MSE'},'剔除共同金价和宏观变化后的残差异常仍未稳定改善预测。','风险基准同时含黄金历史风险、宏观和 GVZ。','该残差只消除了所列线性共同因素，并非纯情绪或结构冲击。')
test(40,'daily_results.json',{'model':'signed','metric':'MSE'},'将比值上行与下行冲击分开没有建立可靠的未来风险不对称优势。','分项样本内风险系数区间均跨零；前推误差也没有改善。')
test(41,'daily_results.json',{'model':'curve','metric':'MSE'},'绝对异常的平方项没有稳定改善线性模型。','所有期限和方向都保留，没有按最佳曲率结果再选择模型。')
test(42,'daily_results.json',{'model':'silver_ratio','metric':'MSE'},'控制白银历史风险后，比值异常没有稳定的额外预测增量。','5 日风险点改善仅约 0.03%，20 日风险和多数其他目标误差上升。','这不能证明白银风险是比值全部信息的唯一来源。')
test(43,'daily_results.json',{'target':'tail_down20','metric':'MSE'},'按当时风险尺度定义的黄金下行尾部事件，没有得到比值特征的稳定提前预警改善。','使用样本外 Brier 误差、强基准及全体候选；不将同期暴跌当作未来预测。','概率模型为裁剪的线性概率模型，尾部样本少；不代表已穷尽所有尾部模型。')
test(44,'daily_results.json',{'target':'tail_up20','metric':'MSE'},'同样检验上行尾部后，也没有可靠的比值增量证据。','对称定义 ±2 倍当时风险尺度，避免把风险增加只解释为下跌。','上下事件次数不同，Brier 误差不能直接等同交易胜率。')
test(45,'daily_results.json',{'model':'down_ratio','metric':'MSE'},'控制已经发生的黄金跌幅后，比值急升未建立稳定的后续反弹或风险预测。','收益与风险目标同时检查，并保留冲击×跌幅交互。')
test(46,'daily_results.json',{'model':'state_ratio','metric':'MSE'},'按历史 GVZ 中位数划分状态后，没有稳定的低隐含风险期比值优势。','阈值只用过去数据，状态基准与含交互模型使用同样日期。')
add(47,'部分年份和极端损失日会影响平均误差，不能将某一窗口的改善直接外推。','逐年保留基准损失和新增模型损失差，另删最差 5 个基准误差日作敏感性检查。','剔除极端日是诊断，不代表危机交易时可以删除这些日子。','daily_contributions.json',[x for x in loadj('daily_contributions.json') if x['target']=='future_logvar20' and x['model']=='standard'])
add(48,'首次与连续异常的未来风险条件系数均接近零，区块区间跨零。','除了分项拟合，还检验两项一起加入基准的样本外误差。','连续状态定义为日频相邻异常；周采样并不覆盖每次事件起点，也没有独立事件随机化。','daily_conditional_coefficients.json',DC['event'])
add(49,'短期相对反转存在部分样本内迹象，但加入其他条件后不构成稳健的反向投资规则。','同时检查相对收益前推误差、正负冲击和完整多因子系数。','样本内比值速度的负系数不能推出做多黄金；相对回归可由白银上涨完成。','daily_conditional_coefficients.json',{'conditional':DC['relative'],'full':FC['future_ratio20']})
test(50,'daily_results.json',{'metric':'QLIKE'},'更换为方差 QLIKE 评分后，没有形成跨目标、跨模型一致的比值优势。','使用同一批预测和训练样本残差重转换，避免拿对数预测直接当无偏方差。','QLIKE 与对数均方误差重视的错误不同；偶然符号变化不够确立优势。')
test(51,'hourly_risk_results.json',{'variant':'main','period':'all','metric':'MSE'},'小时代理中，1 日异常压力出现小幅点改善，5 日未保持；未确立稳定风险预测能力。','三特征、两个期限、两种基准全部记录并校正多重检验。','1 日仅 156 个、5 日仅 140 个信号；缺失重大极端日，且不是原论文压力指标的复制。')
test(52,'hourly_risk_results.json',{'variant':'main','period':'all','baseline':'cross','metric':'MSE'},'加入白银自身分时风险后，原始幅度与标准幅度的改善消失；压力代理仍有短期迹象但不稳健。','所有模型保持共同样本，避免样本范围改变造成假改善。','换基准不保证完全隔离信息来源；白银风险与比值特征相关。')
test(53,'hourly_risk_results.json',{'variant':'with_overnight','period':'all','metric':'MSE'},'纳入隔夜平方项后结果需要单独解释，不能把美股时段内结论直接当全天金价风险结论。','沿用同一特征，只改变风险目标，保留全部结果。','隔夜净变化平方并不是逐小时国际夜盘实现方差。')
test(54,'hourly_risk_results.json',{'variant':'gap_one_day','period':'all','metric':'MSE'},'留出完整交易日的检验没有给出普遍、稳定的比值压力优势。','先前日数据和目标间留空档，减少紧邻波动持续性的误读。','空档同时可能丢失真实但很短的作用，不能据此排除分钟级机制。')
test(55,'hourly_risk_results.json',{'variant':'other_issuer','period':'all','metric':'MSE'},'换用 IAU/SIVR 后仍未建立跨期限和基准一致的异常比值优势。','独立重建报价、分时收益、目标与所有候选特征。','不同 ETF 共同经历同一市场，不能当成独立经济实验；缺失日期也相同。')
add(56,'白银过去一两段收益加入黄金模型，黄金后续时段收益误差约增加 0.115%；未形成领先证据。','更换 ETF 后约增 0.124%；按日评价而非把每根时段都当独立样本。','小时频率会漏掉秒或分钟内的真实传播，也只覆盖纽约 ETF 时段。','hourly_lead_results.json',[x for x in HR['main'] if x['metal']=='g' and x['kind']=='return' and x['period']=='all'])
add(57,'黄金滞后收益对后续白银收益有约 0.34% 的微小点改善，未通过不确定性与多重检验。','另一对 ETF 的改善约 0.26%，保留两个年份分解。','方向上的微小统计改善不等于有净收益或识别了资金主导者。','hourly_lead_results.json',[x for x in HR['main'] if x['metal']=='s' and x['kind']=='return' and x['period']=='all'])
add(58,'黄金过去的平方收益对白银下一时段风险有约 5.4% 点改善，强于方向改善，但区间和校正不足以确证。','反向白银→黄金并未改善；另一对 ETF 点改善约 5.0%。','平方收益目标很噪，极端事件遗漏和短样本使“波动传递”只能保留为待验证方向。','hourly_lead_results.json',[x for x in HR['main'] if x['kind']=='variance' and x['period']=='all'])
add(59,'时段切分显示先后表现有时间依赖，不能把全日平均当每小时都有效。','上午、下午分别按日汇总评分，两个方向和两个目标全部保留。','时段子样本也是探索性多次比较，未从中选择交易窗口。','hourly_lead_results.json',[x for x in HR['sections'] if x['section'] in ['morning','afternoon']])
add(60,'极端误差日敏感性揭示领先幅度的不稳定，不能仅凭全样本一点改善断言主导顺序。','删除每个基准模型最差 5 个交易日再比较；与保留极端日结果并列。','这个剔除仅用于解释误差来源，不能作为实时筛选规则。','hourly_lead_results.json',[x for x in HR['sections'] if x['section']=='exclude_top5_error_days'])
add(61,'最后半小时必须区别对待；评分换为每分钟方差后，依然需保留区间与不确定性。','模型包含时段控制；另把实际与预测平方收益除以分钟数后按日重新评分。','按长度转换后的误差不是新的独立数据，不能另算一次独立发现。','inference_audit.json',IA['duration_score_audit'])
add(62,'日终相对变化很小不等于日内分歧很小；样本存在终点平静、路径平方变化较高的日期。','以开收盘比值绝对变化的低四分位和日内平方变化高四分位作交叉事件。','四分位阈值为全样本描述，未冒充事先可用的交易规则。','measurement_results.json',{p:x['calm_endpoint_busy_path'] for p,x in M['hourly_measurement'].items()},'测量','局部样本支持')
add(63,'大幅同动更多发生于同一采样时段，支持先检查共同冲击，而非先假定一方提前。','GLD/SLV 中同段双异常 85 次，黄金异常后下一段白银异常 36 次；尺度只用过去同一时段。','事件计数机会数、尾盘无下一段等不同；不能把 85/36 当正式相对概率或因果统计。','hourly_lead_results.json',HR['descriptions'],'实证','描述性支持')
add(64,'2025 与 2026 的表现不能视作稳定迁移验证；风险预测中的 2025 可评价区间尤其短。','全部候选按年份展开，不只报告最好年份。','小时数据 2026 漏掉重大暴跌日；两个年份也不足以覆盖长期不同市场状态。','hourly_risk_results.json',[x for x in loadj('hourly_risk_results.json') if x['variant']=='main' and x['period']!='all' and x['metric']=='MSE'])
add(65,'367 个交易日的时段预测不应包装为 1,835 个独立样本；窗口重叠也需要区块推断。','并列逐段独立标准误、逐日标准误，以及 1/10/20/40 日区块结果。','区块法只能缓解局部相关，不能修复缺失极端日或消除结构断点。','inference_audit.json',IA['precision_audit'],'统计审计','方法要求明确')
add(66,'基金净合约变化与同期价格关系在控制宏观后仍需解释为条件关联，不能当先行动证据。','分别估计黄金与白银的同期系数，并对照公开延迟持仓的样本外结果。','截至日内的价格与持仓同时形成，方向识别仍缺少高频订单与外生冲击。','fund_coefficients.json',{k:v for k,v in FU.items() if k.endswith('net_contemporaneous')},'实证','同期关系支持，因果未定')
add(67,'净持仓把平多和加空压缩为同一个数字，分项回归提供不同的同期条件系数。','同时估计多头与空头合约变化，避免只从净额推断行为。','分项聚合仍无法看到单个机构开平仓、跨市场对冲或交易先后。','fund_coefficients.json',{k:v for k,v in FU.items() if k.endswith('long_short_contemporaneous')})
test(68,'fund_results.json',{'metric':'MSE'},'生产商、掉期商、其他报告者与管理基金没有共同、稳定的领先效果，不能统一叫作一个主力。','所有类别使用相同可用时钟、目标和基准；同时检查多空会计约束。','类别是监管报告口径，不直接等于投机、套利、做市或真实意图。')
test(69,'fund_results.json',{'model':'spread','metric':'MSE'},'跨期套利持仓比例未提供稳定风险改善；个别尾部点改善不具普遍性。','收益、风险、比值和上下尾部全部比较。','COT spreading 是配对持仓分类，不是买卖价差、成交量或统一押注方向。')
test(70,'fund_results.json',{'model':'crowding','metric':'MSE'},'金银基金相对拥挤指标未稳定预测后续比值或黄金收益。','各自按过去 156 周标准化，再比较差值，避免金银合约数量直接相减。','过去分布也会变，标准化不会使不同类别持仓变成同一美元风险单位。')
test(71,'fund_results.json',{'model':'tails','metric':'MSE'},'历史极端基金头寸没有在本样本建立稳定的黄金尾部提前预警。','同时检验上下尾部及均值收益；未把同期极端关系当预测。','极端事件少，不能否认更细持仓或更长样本可能包含信息。')
test(72,'fund_results.json',{'model':'managed','metric':'MSE'},'在保守公开时钟下，管理基金变量对黄金未来风险和收益均未稳定改善预测。','同一样本比较风险、方向和尾部目标，而不只选择其中一种。','公开持仓缺少成交、盘中变动和场外敞口，不能推论真实基金决定没有影响。')
add(73,'价格或比值可能与后续多空调整有关，但本次没有建立跨金银、跨分项稳定的价格→资金预测规则。','新做条件系数分解，并与前序完整前推预测、族内校正对照。','反向回归使用截至日信息，属事后机制分析；不是当日公众能看到完整持仓的策略。','fund_coefficients.json',{k:v for k,v in FU.items() if k.endswith('reverse')})
add(74,'类别持仓可以提取共同统计成分，但主成分不等于一位统一决策者。','对四类净合约变化标准化做 PCA，同时检查对手方会计关系。','特征向量符号可整体翻转，类别间负载可能只是多空对手关系；不能解释为机构身份。','fund_structure.json',loadj('fund_structure.json'),'结构审查','可压缩，主体不可识别')
add(75,'多头和空头同时减少与单纯看空不同，常伴随未平仓量收缩。','统计同时收缩的周期及 OI 变化，并独立检验其未来收益和风险增量。','同时收缩可来自去杠杆、到期或再配置；没有交易者级别数据无法唯一归因。','fund_structure.json',loadj('fund_structure.json'))
add(76,'样本中有 13 个周一和 1 个周三截至日，加上停发追补，简单按每周二／周五固定移动会出错。','实际截至日期与常规星期分别核对，并对官方特别公告列明的窗口排除。','没有全部实际发布时间；周历异常检查不能替代原始发布档案。','measurement_results.json',M['timing'],'日历审计','明确限制')
lit(77,['L13'],'不等公开发布就使用截至日持仓会夸大可交易信息集。','前序截至日与保守延迟模型分开；本批次统一使用延迟时钟并保留修订限制。','截至日模型可以研究同期机制，但不能冒充实时投资可取得的数据。')
add(78,'周五尾盘风险与其他日之差在不同 ETF 间不一致，不能归因于 COT 发布。','按分钟比较最后半小时与前六段风险，排除已知 2025 年末停发窗口。','这里只做星期日历关联，没有精确发布事件匹配、公告意外值和对照日识别。','hourly_lead_results.json',{p:v['friday_close_risk'] for p,v in HR['descriptions'].items()})
add(79,'相同类别净增 10 的汇总，可以来自单个账户加 10，也可以来自一账户加 110、另一账户减 100。','构造汇总完全相同但行为路径不同的反例，再对照 COT 聚合层级。','即使知道更多周末多空总数，也不能恢复周内订单顺序、动机和场外对冲。','literature_sources.json',{'sources':['L06','L13'],'path_A':[10,0],'path_B':[110,-100]},'不可识别性反例','确定')
lit(80,['L12','L06','L03'],'要识别资金冲击因果，需要细时间戳和可验证的外生变化，或可信的工具变量／事件设计。','审查宏观意外、持仓强度内生性、价格发现与订单身份的区别。','公告意外可以较外生，但不能据此让原本内生的基金持仓自动变成随机处理。')
lit(81,['L01'],'2026 年论文提供正面风险预测证据，但当前免费可得材料不足以严格复现。','逐项对照期货 versus ETF、2009—2025 versus 两年、原压力指标 versus AR 代理、日内 RV versus 小时平方和。','本次弱结果不能推翻该论文；文献正结果也不能直接变成金价买卖或机构因果规则。')
lit(82,['L01','L02'],'有符号冲击与异常幅度可产生不同效应，不一定是版本互相矛盾。','按研究对象、符号、风险目标和版本时间逐项比较。','同一作者工作稿、会议摘要、修订稿不是三次独立重复验证。')
lit(83,['L03'],'永久信息进入、较少报价噪声、可预测下一段收益分别定义了不同的“领先”。','原文一分钟中间报价和不同价格发现指标与本次小时收益模型对照。','黄金期货相对黄金现货的价格发现不等于黄金相对白银领先，更不是基金决定先后。')
lit(84,['L04'],'独立搜索情绪研究更支持风险与跳跃通道，不能据此把比值速度直接等同恐慌强度。','对照情绪代理、日内和日线频率以及尾部分布方法。','本次没有 FEARS 全序列，也不声称复现其非参数分位数方法。')
lit(85,['L05'],'公告附近金银流动性反应不同，为短时比值异动提供可行解释。','核对事件时点与不同恢复速度，区别公告意外和预期中的撤单。','共同公告下的先后变化不自动等于私人资金预知消息。')
lit(86,['L06'],'交易动机和流动性渠道存在异质性，公开周度净头寸难以识别这些机制。','核对原研究使用的个体日终私有数据和本次公开 COT 的信息差距。','原研究横跨多商品，不能将某类平均效果机械套入每一次金银比波动。')
lit(87,['L07','L08'],'持仓文献分歧部分来自现货／期货、旧分类／管理基金、短期／月度及前后时期的差异。','两篇原研究的样本与预测对象逐项并列，保留极端持仓和早期样本的例外。','并非所有分歧都已解释，也不能将无 Granger 关系写成没有真实价格影响。')
lit(88,['L09','L15'],'59.65 等均衡数值是特定模型估计，不能成为永久投资阈值。','与本次跨期中位数、长期斜率和 AR 半衰期不稳定性核对。','本研究未复制报告的全部协整方法，因此不将不同参数直接称为报告错误。')
lit(89,['L10'],'央行储备需求是黄金相对白银的一条结构渠道，可使历史参照改变。','区分官方披露与未披露购买估计，并检查统计发布频率。','无法从年度购买总量单独估计金银比中的央行因果贡献率。')
lit(90,['L11'],'工业用途、节银与替代意味着白银相对价格包含经济与技术信息，不是纯金融情绪。','核对装机增长与金属用量可以反向变化的原始行业证据。','物理需求变化对价格的作用还取决于库存、供给、投资需求及预期，不能一对一归因。')
for i,target,label in [(91,'future_return20','黄金未来收益'),(92,'future_logvar20','黄金未来对数方差'),(93,'future_ratio20','比值未来收益')]:
 add(i,f'{label}完整 17 因子模型已估计，753 个周信号，提供每一标准差系数与 95% 区块区间。','样本内系数与前推消融结果并列；51 个主系数另做整体多重比较。','系数是条件关联，非因果或固定权重；样本内 R² 不等于可交易预测能力。','factor_coefficients.json',FC[target])
add(94,'完整模型标准化条件数约 5.75，最高 VIF 约 5.68；存在中等共线性但没有比值恒等式造成的精确退化。','省略完整因子组、加入更多宏观因子及固定收缩分别检查。','VIF 较小也不能排除遗漏变量、内生性或参数随时期改变。','factor_coefficients.json',{k:{'condition':v['condition_number_standardized'],'vif':{x['factor']:x['vif'] for x in v['coefficients'][1:]}} for k,v in FC.items() if not k.endswith('extended')},'模型审计','样本明确')
add(95,'增加铜、油和通胀预期未带来整体稳定的前推改善；核心比值系数仍需看区间。','扩展与原模型使用同样样本；原系数变化和预测误差一并保存。','三个代理不足以穷尽供需、央行、地缘及市场微观因素。','factor_coefficients.json',{k:v for k,v in FC.items() if k.endswith('extended')})
add(96,'固定前后分期的系数存在变化，完整模型不宜解释为不变的经济常数。','使用 2009—2018 与 2019—2025 的固定分期，报告全部区间而非挑最佳窗口。','分期样本减少、解释变量自身标准差不同；比较结构大小应同时参考原单位系数。','factor_period_coefficients.json',loadj('factor_period_coefficients.json'))
test(97,'factor_results.json',{'metric':'MSE'},'固定 ridge 收缩能缓解部分过拟合，非线性项没有普遍改善；收缩也未通过跨全体比较的校正。','只采用固定惩罚 10 和预设平方、状态交互，没有参数搜索。','收缩优于较复杂 OLS 不等于比值产生新的可交易信息，仍需对照简单基准。')
test(98,'factor_results.json',{'metric':'MSE'},'按整组消融，宏观及期权信息对风险的点改善最明显；新增比值／资金组未确立稳定增量。','统一 509 个前推信号；完整组删除比较与单变量系数分开解释。','宏观组改善在严格全局校正后也未达 5%；不把组内结果当全局确认。')
add(99,'206 个新增全期主预测比较中，12 个原始 p<0.05，整体 Holm 校正后为 0。','涵盖全部全期 MSE 比较及替代日内口径；分年、时段及 QLIKE 仅作诊断，未挑选成为新发现。','校正保守且样本有限；不能把未通过校正解释成真实效应必然为零。','inference_audit.json',{'n':IA['primary_forecast_comparisons'],'raw':IA['raw_p_below_05'],'adjusted':IA['global_holm_below_05'],'minimum_global_p':min(x['global_holm_p'] for x in IA['tests'])},'统计审计','明确结果')
add(100,'独立重算目标、预测、误差和系数通过；100 项均有问题、证据、反证检查与边界记录。','29,625 个日线目标值、23,432 个日内目标或组成值、696 个模型重估、206 个误差比较、117 个系数独立核对。','通过内部审计不等于原始供应商没有修订，也不补足缺失的个体订单与完整发布历史。','verification.json',loadj('verification.json'),'独立复核','内部复核通过')
assert set(rows)==set(range(1,101))
ordered=[rows[i] for i in range(1,101)]
for r in ordered:
 assert all(r[k] for k in ['finding','countercheck','limitation','evidence','evidence_file'])
 assert (ROOT/r['evidence_file']).exists()
save('100项研究台账.json',ordered)
lines=['# 100 项研究台账','', '完成的是 100 个预先列明的研究问题，并非 100 个独立经济样本或 100 次成功发现。公式验证、测量审计、实证和文献审查分别标注。未能确立效应、存在反证或无法识别因果，均如实保留；下载失败和同一模型的小幅调参不另算研究单元。','', '每项结构化证据和完整数值见同名 JSON 及所指结果文件；外部来源访问范围见《文献核对》。']
for r in ordered:
 lines += ['',f"**{r['id']:03d} · {r['question']}**",'',f"类别：{r['kind']}；证据等级：{r['evidence_strength']}。",f"检验：{r['method']}",f"结果：{r['finding']}",f"反证／复核：{r['countercheck']}",f"边界：{r['limitation']}",f"证据：[结果文件]({(ROOT/r['evidence_file']).as_posix()})；结构化台账第 {r['id']} 项。"]
(ROOT/'100项研究台账.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
save('completion_audit.json',{'units':len(ordered),'unique_questions':len({r['question'] for r in ordered}),'completed':sum(r['status']=='completed' for r in ordered),
 'groups':dict(Counter(r['group'] for r in ordered)),'all_evidence_files_exist':True,'numerical_verification_passed':loadj('verification.json')['passed'],
 'manifest_preserved':True,'source_records':len(sources),'note':'Research completion does not imply every hypothesis is established. No claim of exhaustive worldwide literature review or 100 independent replications.'})
print('100 research records complete; all evidence files and numerical verification present.')
